services:
  - docker

language: go

os:
  - linux

go:
  - "1.10"

script:
  - make tools
  - curl https://raw.githubusercontent.com/golang/dep/1550da37d8fab9ed2dbc4bd04290e6c8dd3ff04a/install.sh | sh
  - make install
  - make travis-build

notifications:
  email: false
