apiVersion: apiextensions.k8s.io/v1alpha
kind: CustomResourceDefinition
metadata:
  name: kuber.vmware.com
spec:
  version: v1
  scope: Cluster
  names:
    singular: kuber
    kind: Kuber
    shortNames:
    - kuber